// <auto-generated />
using GrpcGreeter.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcGreeter.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20241009121800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcGreeter.DbModels.Message", b =>
                {
                    b.Property<string>("PRSeqNum")
                        .HasColumnType("text")
                        .HasColumnName("ud_num");

                    b.Property<double>("Decimal1")
                        .HasColumnType("double precision")
                        .HasColumnName("dec_1");

                    b.Property<double>("Decimal2")
                        .HasColumnType("double precision")
                        .HasColumnName("dec_2");

                    b.Property<double>("Decimal3")
                        .HasColumnType("double precision")
                        .HasColumnName("dec_3");

                    b.Property<double>("Decimal4")
                        .HasColumnType("double precision")
                        .HasColumnName("dec_4");

                    b.Property<int>("PacketSeqNum")
                        .HasMaxLength(128)
                        .HasColumnType("integer")
                        .HasColumnName("packet_seq_num");

                    b.Property<string>("PacketTimestamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("packet_timestamp");

                    b.Property<int>("RecordSeqNum")
                        .HasMaxLength(128)
                        .HasColumnType("integer")
                        .HasColumnName("record_seq_num");

                    b.Property<string>("RecordTimestamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_timestap");

                    b.HasKey("PRSeqNum")
                        .HasName("pkey");

                    b.ToTable("grpc_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
