apiVersion: apps/v1
kind: Deployment
metadata:
  name: ManifestByWeb-app
spec:
  selector:
    matchLabels:
      app: ManifestByWeb-app
  template:
    metadata:
      labels:
        app: ManifestByWeb-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLables:
              app: ManifestByWeb-app
      containers:
        - name: ManifestByWeb-app
          image: ManifestByWeb-app:v1
          resources:
            requests:
              memory: "128M" #величина по условию
              cpu: "100m" #в условии нет данной величины, только 0,1CPU, взяла примерно
            limits:
              memory: "256M" #величина по условию*2 (на пиковые нагрузки при инициализации)
              cpu: "200m" #в условии нет этой величины, взяла примерно средняя*2 (аналогично)
          ports:
            - containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10 #по условию 5-10 секунд
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 5
