version: '3.5'
networks:
  grpc_client:
    driver: bridge
    ipam:
      config:
        - subnet: 172.7.0.0/16
services:
  grpc_client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - grpc_client    
